metadata:
  labels:
    app: JSO-ARQUETIPOS
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'default'
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8181
              name: actuator
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 140
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 140
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: '200m'
              memory: '350Mi'
            requests:
              cpu: '100m'
              memory: '192Mi'
          volumeMounts:
          - name: application-config
            mountPath: /deployments/config
      volumes:
        - name: application-config
          configMap:
            name: cm-jso-fwk-hello-service